name: Chartink Alerts

on:
  schedule:
    # Runs every 5 minutes during market hours on weekdays (9:30 AM - 3:30 PM)
    - cron: '*/5 4-10 * * 1-5' # Times are in UTC (9:30 AM to 3:30 PM IST = 4:00 AM to 10:30 AM UTC)

  workflow_dispatch:

jobs:
  run-chartink-alerts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Chartink Alerts
      env:
        CHARTINK_CONDITION: ${{ secrets.CHARTINK_CONDITION }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python -m stock_scanner.main
